# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

snipcart:
  key: SNIPCART_TEST_KEY

stylesheeets:
  - assets/css/linearicons.css
  - assets/css/font-awesome.min.css
  - assets/css/themify-icons.css
  - assets/css/bootstrap.css
  - assets/css/owl.carousel.css
  - assets/css/nice-select.css
  - assets/css/nouislider.min.css
  - assets/css/ion.rangeSlider.css
  - assets/css/ion.rangeSlider.skinFlat.css
  - assets/css/magnific-popup.css
  - assets/css/main.css

scripts:
  - assets/js/vendor/jquery-2.2.4.min.js
  - assets/js/vendor/bootstrap.min.js
  - assets/js/jquery.ajaxchimp.min.js
  - assets/js/jquery.nice-select.min.js
  - assets/js/jquery.sticky.js
  - assets/js/nouislider.min.js
  - assets/js/countdown.js
  - assets/js/jquery.magnific-popup.min.js
  - assets/js/owl.carousel.min.js
  - assets/js/gmaps.min.js
  - assets/js/main.js

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - _pages
