backend:
  name: git-gateway
  branch: main

media_folder: assets/images

collections:
  - name: product
    label: Product
    folder: _products
    create: true
    fields:
      - label: "Identifier"
        name: identifier
        widget: string
      - label: "Name"
        name: name
        widget: string
      - label: "Price"
        name: price
        widget: number
      - label: "Image"
        name: image
        widget: image
      - label: "Body"
        name: body
        widget: markdown